[tcp]
address = "127.0.0.1:5004"
[mysql]
[mysql.user]
username = "root"
password = "123456"
ip = "127.0.0.1"
port = "3306"
dbname = "user"
[mysql.test]
username = "root"
password = "123456"
ip = "127.0.0.1"
port = "3306"
dbname = "test"

[redis]
[redis.user]
addrss = "127.0.0.1:6379"